#!/usr/bin/env python3
"""
手动测试启动器 - 解决shell问题
"""

print("🔧 手动迁移测试启动器")
print("=" * 60)

print("由于shell环境存在问题，请按以下步骤手动运行测试：")
print()

print("步骤1: 打开终端")
print("cd /Users/syu/workdata/person/zy/RANGEN-main\\(syu-python\\)")
print()

print("步骤2: 启动Python解释器")
print("python3")
print()

print("步骤3: 在Python提示符>>>下执行以下代码：")
print()
print("import asyncio")
print("import sys")
print("import os")
print("import time")
print()
print("# 设置项目路径")
print("project_root = '/Users/syu/workdata/person/zy/RANGEN-main(syu-python)'")
print("sys.path.insert(0, project_root)")
print("os.chdir(project_root)")
print()
print("# 加载环境变量")
print("env_file = '.env'")
print("if os.path.exists(env_file):")
print("    with open(env_file, 'r') as f:")
print("        for line in f:")
print("            line = line.strip()")
print("            if line and not line.startswith('#') and '=' in line:")
print("                key, value = line.split('=', 1)")
print("                os.environ[key.strip()] = value.strip().strip('\"').strip(\"'\")")
print("    print('✅ 环境变量加载成功')")
print("else:")
print("    print('❌ 未找到.env文件')")
print()
print("# 导入并运行测试")
print("async def test():")
print("    try:")
print("        from src.agents.expert_agents import KnowledgeRetrievalAgent")
print("        from src.agents.rag_agent import RAGExpert")
print("        from src.adapters.knowledge_retrieval_agent_adapter import KnowledgeRetrievalAgentAdapter")
print("        from src.strategies.gradual_replacement import GradualReplacementStrategy")
print("        print('✅ 组件导入成功')")
print("        ")
print("        old_agent = KnowledgeRetrievalAgent()")
print("        new_agent = RAGExpert()")
print("        adapter = KnowledgeRetrievalAgentAdapter()")
print("        strategy = GradualReplacementStrategy(old_agent, new_agent, adapter)")
print("        print('✅ 实例创建成功')")
print("        ")
print("        for rate in [0.0, 0.5, 1.0]:")
print("            print(f'\\n🔄 测试替换比例: {rate:.0%}')")
print("            strategy.replacement_rate = rate")
print("            ")
print("            context = {")
print("                'query': f'测试查询 - 比例{rate:.0%}',")
print("                'max_iterations': 1,")
print("                'use_tools': False,")
print("                'enable_knowledge_retrieval': False")
print("            }")
print("            ")
print("            start = time.time()")
print("            result = await strategy.execute_with_gradual_replacement(context)")
print("            duration = time.time() - start")
print("            ")
print("            executed_by = result.get('_executed_by', 'unknown')")
print("            success = result.get('success', False)")
print("            ")
print("            agent_icon = '🤖' if executed_by == 'old_agent' else '🆕'")
print("            status_icon = '✅' if success else '❌'")
print("            ")
print("            print(f'   {status_icon} {agent_icon} {executed_by}: {duration:.3f}s')")
print("            await asyncio.sleep(1.0)")
print("        ")
print("        print('\\n🎉 测试完成！')")
print("    except Exception as e:")
print("        print(f'❌ 错误: {e}')")
print("        import traceback")
print("        traceback.print_exc()")
print()
print("asyncio.run(test())")
print()

print("=" * 60)
print("📋 说明：")
print("1. 复制上面的代码到Python解释器中")
print("2. 按行执行（或者一次性粘贴所有代码）")
print("3. 观察测试结果")
print("4. 如果遇到错误，请告诉我具体的错误信息")
print("=" * 60)
