#!/usr/bin/env python3
"""
LiteConfigurator - 轻量配置器

快速配置 RANGEN Lite 模式
"""
import os
import sys
from pathlib import Path
from typing import Optional, Dict, Any


class LiteConfigurator:
    """轻量配置器"""
    
    def __init__(self, config_path: Optional[str] = None):
        self.config_path = config_path or ".env"
        self.config: Dict[str, str] = {}
    
    def configure(self, **kwargs) -> bool:
        """配置系统
        
        Args:
            provider: LLM provider (deepseek, openai, mock)
            api_key: API key
            model: Model name
            port: UI port
            
        Returns:
            是否配置成功
        """
        try:
            # 设置默认值
            self.config["LLM_PROVIDER"] = kwargs.get("provider", "mock")
            self.config["LLM_MODEL"] = kwargs.get("model", "deepseek-chat")
            self.config["LLM_API_KEY"] = kwargs.get("api_key", "")
            self.config["RANGEN_PORT"] = str(kwargs.get("port", "8501"))
            self.config["RANGEN_LITE_MODE"] = "true"
            
            # 保存配置
            return self._save_config()
        except Exception as e:
            print(f"配置失败: {e}")
            return False
    
    def _save_config(self) -> bool:
        """保存配置到 .env 文件"""
        try:
            with open(self.config_path, "w") as f:
                f.write("# RANGEN Lite Configuration\n")
                f.write("# Generated by LiteConfigurator\n\n")
                for key, value in self.config.items():
                    f.write(f"{key}={value}\n")
            print(f"✅ 配置已保存到 {self.config_path}")
            return True
        except Exception as e:
            print(f"保存配置失败: {e}")
            return False
    
    def load_config(self) -> Dict[str, str]:
        """加载现有配置"""
        if not os.path.exists(self.config_path):
            return {}
        
        with open(self.config_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    self.config[key.strip()] = value.strip()
        
        return self.config


def interactive_configure():
    """交互式配置"""
    print("\n" + "=" * 50)
    print("RANGEN Lite 配置向导")
    print("=" * 50)
    
    configurator = LiteConfigurator()
    
    # 检查现有配置
    existing = configurator.load_config()
    if existing:
        print("\n发现现有配置:")
        for k, v in existing.items():
            if "KEY" not in k:
                print(f"  {k}={v}")
        print()
    
    # 交互式输入
    provider = input(f"LLM Provider [{existing.get('LLM_PROVIDER', 'mock')}]: ").strip()
    if not provider:
        provider = existing.get("LLM_PROVIDER", "mock")
    
    api_key = input("API Key: ").strip()
    if not api_key:
        api_key = existing.get("LLM_API_KEY", "")
    
    model = input(f"Model [{existing.get('LLM_MODEL', 'deepseek-chat')}]: ").strip()
    if not model:
        model = existing.get("LLM_MODEL", "deepseek-chat")
    
    port = input(f"UI Port [{existing.get('RANGEN_PORT', '8501')}]: ").strip()
    if not port:
        port = existing.get("RANGEN_PORT", "8501")
    
    # 执行配置
    success = configurator.configure(
        provider=provider,
        api_key=api_key,
        model=model,
        port=port
    )
    
    if success:
        print("\n✅ 配置完成！运行 'python -m src.cli lite' 启动")
    else:
        print("\n❌ 配置失败")


def quick_start():
    """快速启动（使用默认配置）"""
    configurator = LiteConfigurator()
    
    if not os.path.exists(".env"):
        print("📝 创建默认配置...")
        configurator.configure(provider="mock")
    
    print("🚀 启动 RANGEN Lite...")
    print("   访问 http://localhost:8501 查看界面")
    print("   或使用 CLI: python -m src.cli chat")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "interactive":
        interactive_configure()
    else:
        quick_start()
